#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 81

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["/LC_Backend/LC_Backend.csproj", "LC_Backend/"]
COPY ["/FhirbaseConnector/FhirbaseConnector.csproj", "FhirbaseConnector/"]
RUN dotnet restore "LC_Backend/LC_Backend.csproj"
COPY . .
WORKDIR "/src/LC_Backend"
RUN dotnet build "LC_Backend.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "LC_Backend.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "LC_Backend.dll"]