server:
  port: 8081

keycloak:
  clientID: "Test1"
  clientSecret: "c31dd103-25ff-42a6-aa3e-7ba5e2d8d7c3"
  #ip: "healthaccesscontrol.eastus2.cloudapp.azure.com"
  ip: "172.29.16.61:8080"
  debugMode: false
  #ip: "http://52.184.137.140:8080/auth/realms/Patients/protocol/openid-connect/token/introspect"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://172.29.16.61:8080/realms/data-facade-app"
      client:
        provider:
          keycloak:
            issuer-uri: "http://172.29.16.61:8080/realms/data-facade-app"
        registration:
          keycloak:
            client-id: "Test1"
            authorization-grant-type: "authorization_code"
            scope: "openid"
  jackson:
    mapper:
      accept-case-insensitive-properties: true

fhir:
  #server-url: "http://pt-n4.fhir.w3.cs.technikum-wien.at/fhir"
  serverUrl: "http://172.29.16.62:5432/"
logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: trace
    #root: info
    ca:
      uhn:
        fhir: error